import os
import csv
import secrets
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
from Crypto.Cipher import AES
from Crypto.Protocol.KDF import HKDF
from Crypto.Hash import SHA256
from Crypto.Random import get_random_bytes
from Crypto.Random.random import randint
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
sentences = [
    "At midnight, a zealous spy quietly followed Jack across busy streets.",
    "The treasure map was found hidden inside a quiet, buzzing old vault.",
    "Quickly, Zoe examined the mysterious jar before it cracked open.",
    "Jumpy foxes guard a secret entrance to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
    "A zebra led the group through a quiet passage to the hidden vault.",
    "The ancient book revealed a secret map to the treasure hidden in a cave.",
    "Quickly, Jack followed the zealous spy to the vault beneath the old zoo.",
    "A quiet river marked the boundary of the hidden treasure’s secret location.",
    "Zoe quickly decoded the message and found the hidden vault’s key.",
    "At dawn, Jack quietly entered the old zoo to search for the hidden map.",
    "The treasure was hidden beneath the quiet, buzzing vault in the old zoo.",
    "Xavier decoded the secret message and quickly found the hidden vault.",
    "At midnight, the spy quietly hid the treasure map inside a buzzing vault.",
    "A quiet figure passed the encrypted message to Jack at the jazz concert.",
    "Zoe discovered the hidden vault by following the ancient map’s clues.",
    "Quickly, the treasure was moved to a new vault in a quiet, hazy forest.",
    "A zealous spy followed Jack through the quiet streets at dawn.",
    "The secret treasure map was hidden inside a quiet, buzzing vault.",
    "Quickly, Zoe examined the encrypted message found in the vault.",
    "Jack quietly followed the zealous spy to the hidden vault in the zoo.",
    "A hazy figure was seen exiting the quiet room with a zebra-striped box.",
    "Zane quickly hid the ancient map in a vault before anyone could see.",
    "The encrypted message was quickly deciphered by Jack and his team.",
    "Xavier’s journey to find the hidden treasure began at dawn’s early light.",
    "A secret code was buried deep inside the quiet forest near a zebra.",
    "Quickly, the detective gathered clues from the mysterious jazz concert.",
    "The vault was quietly opened by Jack using an ancient, encrypted key.",
    "At dusk, Zoe quietly passed the mysterious note to a hazy figure.",
   

] 

# Function to save dataset
def save_to_csv(file_name, data):
    with open(file_name, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['plaintext', 'ciphertext', 'algorithm', 'key'])
        for row in data:
            writer.writerow(row)



# Key exchange functions
def diffie_hellman_key_exchange():
    # Simulate Diffie-Hellman key exchange (simplified)
    p = 23  # Prime number (usually much larger in practice)
    g = 5   # Generator
    a = randint(1, p - 1)
    b = randint(1, p - 1)
    A = pow(g, a, p)
    B = pow(g, b, p)
    shared_secret_a = pow(B, a, p)
    shared_secret_b = pow(A, b, p)
    return hex(shared_secret_a), hex(shared_secret_b), 'Diffie-Hellman'

def ecdh_key_exchange():
    # Elliptic Curve Diffie-Hellman (ECDH) key exchange
    private_key = ec.generate_private_key(ec.SECP256R1())
    public_key = private_key.public_key()
    peer_private_key = ec.generate_private_key(ec.SECP256R1())
    peer_public_key = peer_private_key.public_key()
    shared_secret = private_key.exchange(ec.ECDH(), peer_public_key)
    shared_secret_key = HKDF(shared_secret, 32, b'', SHA256)
    cipher = AES.new(shared_secret_key, AES.MODE_EAX)
    encrypted_secret = cipher.encrypt(shared_secret)
    return encrypted_secret.hex(), private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo
    ).hex(), 'ECDH'

def rsa_key_exchange():
    # RSA key pair generation and encryption
    key = RSA.generate(2048)
    cipher = PKCS1_OAEP.new(key)
    shared_secret = get_random_bytes(32)
    encrypted_secret = cipher.encrypt(shared_secret)
    return encrypted_secret.hex(), key.export_key().hex(), 'RSA'

def mqv_key_exchange():
    # Simplified MQV key exchange simulation
    private_key = ec.generate_private_key(ec.SECP256R1())
    public_key = private_key.public_key()
    peer_private_key = ec.generate_private_key(ec.SECP256R1())
    peer_public_key = peer_private_key.public_key()
    shared_secret = private_key.exchange(ec.ECDH(), peer_public_key)
    # In a real MQV, we would perform more steps and use hash functions
    return shared_secret.hex(), public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo
    ).hex(), 'MQV'

def sts_key_exchange():
    # Simplified STS key exchange simulation
    private_key = ec.generate_private_key(ec.SECP256R1())
    public_key = private_key.public_key()
    peer_private_key = ec.generate_private_key(ec.SECP256R1())
    peer_public_key = peer_private_key.public_key()
    shared_secret = private_key.exchange(ec.ECDH(), peer_public_key)
    # STS involves additional steps like signing and verification
    return shared_secret.hex(), public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo
    ).hex(), 'STS'

# Generate dataset
def generate_dataset():
    dataset = []
    for sentence in sentences:
        dataset.append((sentence, *diffie_hellman_key_exchange()))
        dataset.append((sentence, *ecdh_key_exchange()))
        dataset.append((sentence, *rsa_key_exchange()))
        dataset.append((sentence, *mqv_key_exchange()))
        dataset.append((sentence, *sts_key_exchange()))
    save_to_csv('key_exchange_algorithms_dataset.csv', dataset)

if __name__ == "__main__":
    generate_dataset()